# Generated by Django 5.0.6 on 2024-06-20 12:01

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('players', '0002_alter_player_options'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='favorite_players',
            field=models.ManyToManyField(to=settings.AUTH_USER_MODEL),
        ),
    ]
