# Generated by Django 5.0.6 on 2024-06-20 12:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('players', '0003_player_favorite_players'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='player',
            name='favorite_players',
        ),
    ]
